### PR TITLE
added set_mode (low, high) for the princess heaters

### PR DESCRIPTION
**Pull request by kvanhoorn**
**Pull request recommendations:**
- [ ] Name your pull request _your-development-type/short-description_. Ex: _feature/read-tiff-files_
- [ ] Link to any relevant issue in the PR description. Ex: _Resolves [gh-12], adds tiff file format support_
- [ ] Provide context of changes.
- [ ] Provide relevant tests for your feature or bug fix.
- [ ] Provide or update documentation for any feature added by your pull request.

Thanks for contributing!

### CODE REVIEW

**Comment by kvanhoorn** [comment]
There is one issue with adding the 'heater' to the model.
It is missing some required fields when the '_handle_device_update' is executed like 'oscillate', 'fan_speed' and 'error'.
I tried to make them optional in the model 'climate_device_state', however this seems breaking it even more.

It is working, but the initial retrieval of the data fails due to the missing dict items, do you have any idea?

**Comment by kvanhoorn** [comment]
#Fixed for now by adding this dirty bit:

```yaml
self._LOGGER.debug(f"Received full device update: {received_message}")
```

```yaml
if 'fan_speed' not in state:                                     
    state['fan_speed'] = 0                                                  
if 'oscillate' not in state:                                              
    state['oscillate'] = False                                     
if 'error' not in state:                                                      
    state['error'] = []                                        
if 'heat_status' not in state:                                        
    state['heat_status'] = "idle"                                     
if 'vent_heat' not in state:                                                  
    state['vent_heat'] = False                                         
if 'silent' not in state:                                         
    state['silent'] = False                                              
if 'heater' not in state:                   
    state['heater'] = False                     
if 'ext_mode' not in state:                                   
    state['ext_mode'] = []                                       
if 'ext_current_temperature' not in state:                       
    state['ext_current_temperature'] = 0                                    
if 'ext_target_temperature' not in state:                                 
    state['ext_target_temperature'] = 0                            
```

```yaml
self._update_last_state(                                                      
    HomeWizardClimateDeviceState.from_dict(state)              
)                                                                     
```

**Comment by kvanhoorn** [comment]
Screenshot 2023-02-07 at 17 09 54
End result is beautiful 😄

**Comment by diricxbart** [comment]
@kvanhoorn What did you use to generate the above shown card in home assistant? I use the Climate card, but don't have buttons for the "low" and "high", I'd like to have the preset mode (ECO or BOOST) also available via buttons instead of via the menu . . . 

FYI: I added support for the Princess Smart Glass Panel Heater preset mode (ECO and BOOST) (see [this](https://github.com/dennis1804/homewizard-climate-hass/pull/5) PR) and slightly improved your suggested bugfix in [this](https://github.com/dennis1804/homewizard-climate-websocket/pull/3) PR on the dennis1804 fork.

**Comment by kvanhoorn** [comment]
Code of the card is like this:

```
control:
  hvac:
    cool: false
    dry: false
    fan_only: false
    heat: true
    heat_cool: false
    'off': true
  fan:
    low: true
    high: true
    'off': false
entity: climate.zolder_achterkant
step_size: 1
type: custom:simple-thermostat
layout:
  step: row
  mode:
    headings: false```

**Pull request closed without merging**
